server:
  port: 8081
spring:
  cloud:
    config:
      enabled: false
  application:
    name: resource-service
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
song-service:
  url: "http://song-app:8080"

eureka:
  instance:
    hostname: localhost
  client:
    enabled: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8083/eureka